services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-net
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-net

  siem:
    build: ./siem
    container_name: siem_analyzer
    restart: always
    volumes:
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      - nginx
    networks:
      - app-net
    env_file:
      - .env

networks:
  app-net:
    driver: bridge

volumes:
  nginx_logs:
